name: CI
on: [push]
jobs:
  test:
    name: Test & Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: ''
      - run: |
          git fetch --prune --unshallow
      - name: checkout
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: install
        run: npm ci
      - name: lint
        run: npm run lint
      - name: build
        run: npm run build
      - name: test
        run: npm test
      - name: fix COV paths
        run: cp test-report.xml test-report2.xml && sed 's/\/home\/runner\/work\/auto-label-merge-conflicts\/auto-label-merge-conflicts/\/github\/workspace/g' test-report2.xml > test-report.xml